name: Test

on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        default: 'World'
      
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo Hello ${{ github.event.inputs.name }}"
