name: Test

on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        default: 'World'
      
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo $TEST
        echo "Hello ${{ github.event.inputs.name }}"
        echo "TEST=some_value" >> $GITHUB_ENV
        echo $TEST
